
static const VINTIO_t VINTIO[] = {
	{ _sendDEFAULT, _recvDEFAULT },	/* 0 */
	{ _sendDEFAULT, _recvDEFAULT },	/* 1 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 2 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 3 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 4 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 5 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 6 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 7 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 8 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 9 (Servo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 10 (Analog) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 11 (Accelerometer) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 12 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 13 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 14 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 15 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 16 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 17 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 18 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 19 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 20 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 21 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 22 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 23 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 24 (RFID) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 25 (RFID) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 26 (RFID) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 27 (RFID) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 28 (RFID) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 29 (LED) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 30 (LED) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 31 (LED) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 32 (GPS) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 33 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 34 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 35 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 36 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 37 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 38 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 39 (Bridge) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 40 (Bridge) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 41 (Encoder) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 42 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 43 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 44 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 45 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 46 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 47 (TemperatureSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 48 (Encoder) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 49 (Encoder) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 50 (Encoder) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 51 (Accelerometer) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 52 (FrequencyCounter) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 53 (IR) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 54 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 55 (Spatial) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 56 (Encoder) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 57 (PHSensor) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 58 (Accelerometer) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 59 (MotorControl) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 60 (AdvancedServo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 61 (AdvancedServo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 62 (AdvancedServo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 63 (AdvancedServo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 64 (Stepper) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 65 (Stepper) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 66 (MotorControl) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 67 (MotorControl) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 68 (AdvancedServo) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 69 (Stepper) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 70 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 71 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 72 (TextLCD) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 73 (InterfaceKit) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 74 (TextLCD) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 75 (TextLCD) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 76 (TextLCD) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 77 (TextLCD) */
	{ sendDIGITALINPUT_PORT, recvDIGITALINPUT_PORT },	/* 78 (VINT) */
	{ sendDIGITALOUTPUT_PORT, recvDIGITALOUTPUT_PORT },	/* 79 (VINT) */
	{ sendVOLTAGEINPUT_PORT, recvVOLTAGEINPUT_PORT },	/* 80 (VINT) */
	{ sendVOLTAGEINPUT_PORT_5V25, recvVOLTAGEINPUT_PORT_5V25 },	/* 81 (VINT) */
	{ sendVOLTAGERATIOINPUT_PORT, recvVOLTAGERATIOINPUT_PORT },	/* 82 (VINT) */
	{ sendADP1000, recvADP1000 },	/* 83 (VINT) */
	{ sendADP1001, recvADP1001 },	/* 84 (VINT) */
	{ sendDAQ1000, recvDAQ1000 },	/* 85 (VINT) */
	{ sendDAQ1000_5V25, recvDAQ1000_5V25 },	/* 86 (VINT) */
	{ sendOUT1000, recvOUT1000 },	/* 87 (VINT) */
	{ sendOUT1001, recvOUT1001 },	/* 88 (VINT) */
	{ sendOUT1002, recvOUT1002 },	/* 89 (VINT) */
	{ sendCURLOOP, recvCURLOOP },	/* 90 (VINT) */
	{ sendDAQ1200, recvDAQ1200 },	/* 91 (VINT) */
	{ sendOUT1100, recvOUT1100 },	/* 92 (VINT) */
	{ sendOUT1100_Failsafe, recvOUT1100_Failsafe },	/* 93 (VINT) */
	{ sendDAQ1300, recvDAQ1300 },	/* 94 (VINT) */
	{ sendDAQ1301, recvDAQ1301 },	/* 95 (VINT) */
	{ sendDAQ1400, recvDAQ1400 },	/* 96 (VINT) */
	{ sendDAQ1500, recvDAQ1500 },	/* 97 (VINT) */
	{ sendVCP1100, recvVCP1100 },	/* 98 (VINT) */
	{ sendDCC1000, recvDCC1000 },	/* 99 (VINT) */
	{ sendDCC1000_POSITIONCONTROL, recvDCC1000_POSITIONCONTROL },	/* 100 (VINT) */
	{ sendDCC1001, recvDCC1001 },	/* 101 (VINT) */
	{ sendDCC1002, recvDCC1002 },	/* 102 (VINT) */
	{ sendDCC1003, recvDCC1003 },	/* 103 (VINT) */
	{ sendDCC1100, recvDCC1100 },	/* 104 (VINT) */
	{ sendDST1000, recvDST1000 },	/* 105 (VINT) */
	{ sendDST1001, recvDST1001 },	/* 106 (VINT) */
	{ sendDST1200, recvDST1200 },	/* 107 (VINT) */
	{ sendENC1000, recvENC1000 },	/* 108 (VINT) */
	{ sendHIN1101, recvHIN1101 },	/* 109 (VINT) */
	{ sendHIN1000, recvHIN1000 },	/* 110 (VINT) */
	{ sendHIN1001, recvHIN1001 },	/* 111 (VINT) */
	{ sendHIN1100, recvHIN1100 },	/* 112 (VINT) */
	{ sendHUM1000, recvHUM1000 },	/* 113 (VINT) */
	{ sendLCD1100, recvLCD1100 },	/* 114 (VINT) */
	{ sendLED1000, recvLED1000 },	/* 115 (VINT) */
	{ sendLUX1000, recvLUX1000 },	/* 116 (VINT) */
	{ sendMOT1100_OLD, recvMOT1100_OLD },	/* 117 (VINT) */
	{ sendMOT1100, recvMOT1100 },	/* 118 (VINT) */
	{ sendMOT1101, recvMOT1101 },	/* 119 (VINT) */
	{ sendPRE1000, recvPRE1000 },	/* 120 (VINT) */
	{ sendRCC1000, recvRCC1000 },	/* 121 (VINT) */
	{ sendREL1000, recvREL1000 },	/* 122 (VINT) */
	{ sendREL1000_Failsafe, recvREL1000_Failsafe },	/* 123 (VINT) */
	{ sendREL1100, recvREL1100 },	/* 124 (VINT) */
	{ sendREL1100_Failsafe, recvREL1100_Failsafe },	/* 125 (VINT) */
	{ sendREL1101, recvREL1101 },	/* 126 (VINT) */
	{ sendSAF1000, recvSAF1000 },	/* 127 (VINT) */
	{ sendSND1000, recvSND1000 },	/* 128 (VINT) */
	{ sendSTC1000, recvSTC1000 },	/* 129 (VINT) */
	{ sendSTC1001, recvSTC1001 },	/* 130 (VINT) */
	{ sendSTC1002, recvSTC1002 },	/* 131 (VINT) */
	{ sendSTC1003, recvSTC1003 },	/* 132 (VINT) */
	{ sendTMP1000, recvTMP1000 },	/* 133 (VINT) */
	{ sendTMP1100, recvTMP1100 },	/* 134 (VINT) */
	{ sendTMP1101, recvTMP1101 },	/* 135 (VINT) */
	{ sendTMP1200, recvTMP1200 },	/* 136 (VINT) */
	{ sendTMP1300, recvTMP1300 },	/* 137 (VINT) */
	{ sendVCP1000, recvVCP1000 },	/* 138 (VINT) */
	{ sendVCP1001, recvVCP1001 },	/* 139 (VINT) */
	{ sendVCP1002, recvVCP1002 },	/* 140 (VINT) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 141 (Hub) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 142 (Hub) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 143 (MeshDongle) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 144 (Hub) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 145 (Hub) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 146 (Hub) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 147 (FirmwareUpgrade) */
	{ sendFIRMWARE_UPGRADE_STM32F0, recvFIRMWARE_UPGRADE_STM32F0 },	/* 148 (VINT) */
	{ sendFIRMWARE_UPGRADE_STM8S, recvFIRMWARE_UPGRADE_STM8S },	/* 149 (VINT) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 150 (FirmwareUpgrade) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 151 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 152 (InterfaceKit) */
	{ sendGENERICVINT, recvGENERICVINT },	/* 153 (VINT) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 154 (Dictionary) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 155 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 156 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 157 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 158 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 159 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 160 (Generic) */
	{ _sendDEFAULT, _recvDEFAULT },	/* 161 (Generic) */
	{ NULL, NULL }
};
